#!/bin/sh

if dmidecode | grep "ThinkPad L14 Gen 2" -q; then
        BLACKDESK_IS_THINKPAD_L14_GEN2=1
fi

# https://unix.stackexchange.com/a/166751
if cat /sys/class/power_supply/*/type | grep Battery -q; then
        BLACKDESK_HAS_BATTERY=1
fi

echo "BLACKDESK_IS_THINKPAD_L14_GEN2=$BLACKDESK_IS_THINKPAD_L14_GEN2"
echo "BLACKDESK_HAS_BATTERY=$BLACKDESK_HAS_BATTERY"
