#!/bin/bash

set -x
set -e
set -o pipefail

OUTPUT=${OUTPUT:=Country.mmdb}

function cleanup() {
	rv=$?

	if [ $rv -eq 0 ]; then
		return
	fi

	rm "$OUTPUT" -f

	return $rv
}

trap cleanup EXIT

mkdir -p "$(dirname "$OUTPUT")"

curl -LJ "https://github.com/Dreamacro/maxmind-geoip/releases/latest/download/Country.mmdb" >"$OUTPUT"
