#!/bin/bash

set -x
set -e
set -o pipefail

REPO=${REPO:=MetaCubeX/mihomo}

CURL=${CURL:=curl}
JQ=${JQ:=jq}

VERSION=${VERSION:=$(${CURL} -s https://api.github.com/repos/${REPO}/releases/latest | jq -r .tag_name)}

ARCH=${ARCH:=amd64}

OUTPUT=${OUTPUT:=clash-meta}

curl -LJ "https://github.com/${REPO}/releases/download/${VERSION}/mihomo-linux-${ARCH}-cgo-${VERSION}.gz" | gunzip > ${OUTPUT}
